---
# This playbook deploys the whole application stack in this site.  

- hosts: backendservers
  sudo: yes
  roles:
  - common
  - rabbitmq
  - mysql

- hosts: frontendservers
  sudo: yes
  roles:
  - common
  - heat
