---
# This playbook deploys the whole application stack in this site.  

- hosts: backendservers
  roles:
  - backend

- hosts: backendmaster
  roles:
    - backend
      dbrole: master

- hosts: backendslave
  roles:
    - backend
      dbrole: slave
      

# Apply common configuration to all hosts
- hosts: backend
  remote_user: ubuntu
  roles:
    - hacommon
    - mysql
    
- hosts: all
  remote_user: root
  roles:
  - common

# Configure and deploy database servers.
- hosts: dbservers
  remote_user: root
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here, 
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers
  remote_user: root
  roles:
  - base-apache
  - web

# Configure and deploy the load balancer(s).
- hosts: lbservers
  remote_user: root
  roles:
  - haproxy

# Configure and deploy the Nagios monitoring node(s).
- hosts: monitoring
  remote_user: root
  roles:
  - base-apache
  - nagios
