---
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_hostname}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: Check if mysql is already installed and clustered
  stat: path=/etc/mysql/clustered
  register: mysql_clustered
  
- include: mysql_clustering.yaml
  when: mysql_clustered.stat.exists != true
  
- name: Install rabbitMQ
  apt: name=rabbitmq-server state=installed
  
- name: Check if RabbitMQ is already clustered
  stat: path=/etc/rabbitmq/clustered
  register: rabbit_clustered
  
- include: rabbitmq_clustering.yaml
  when: rabbit_clustered.stat.exists != true

  
