---
- name: Prepare system for adding repositories
  apt: name=software-properties-common state=installed update_cache=yes

- name: Add MariaDB repository key
  # only valid after ansible 1.6 apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
  # complains: apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db
  command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  
- name: Add MariaDB repositories for Galera packages
  apt_repository: repo='deb http://mariadb.mirror.nucleus.be//repo/5.5/ubuntu trusty main' state=present update_cache=yes

- name: Install MariaDB and Galera
  apt: name={{ item }} state=installed 
  with_items:
    - mariadb-galera-server 
    - galera   

- name: Update my.cnf file
  ini_file: 
    dest: /etc/mysql/my.cnf
    section: mysqld
    option: {{ item.option }}
    value: {{ item.value }}
    backup: yes
  with_items:
    - { option: 'query_cache_size', value: '0' }
    - { option: 'binlog_format', value: 'ROW' }
    - { option: 'default_storage_engine', value: 'InnoDB' }
    - { option: 'innodb_autoinc_lock_mode', value: '2' }
    - { option: 'innodb_doublewrite', value: '1' }
    

- name: Generate wsrep config file
  template: src=wsrep.cnf.j2 dest=/etc/mysql/conf.d/wsrep.cnf 

- name: Check if local debian.cnf file already exists
  local_action: stat path=/tmp/debian.cnf
  register: mysql_debconf_done
  
- name: Get masters debian.cnf file
  fetch: dest=/tmp/debian.cnf src=/etc/mysql/debian.cnf flat=yes
  notify: Copy debian.cnf to slave
  when: dbrole == 'master' and not mysql_debconf_done.stat.exists
  
- name: Copy masters debian.cnf to slave
  copy: src=/tmp/debian.cnf dest=/etc/mysql/debian.cnf backup=yes
  when: dbrole == 'slave' and mysql_debconf_done.stat.exists

- name: Stop mysql cluster
  service: name=mysql state=stopped

- name: Start master node
  service: name=mysql state=started args=--wsrep-new-cluster
  when: dbrole == 'master'
  
- name: Start slave node
  service: name=mysql state=started
  when: dbrole == 'slave'
  


  
  
