---
- name: Build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{hostvars[item].ansible_hostname}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

- name: Check if mysql is already installed and clustered
  stat: path=/etc/mysql/clustered
  register: mysql_clustered
  
- include: mysql_clustering.yaml
  when: mysql_clustered.stat.exists != true
  
- name: Make sure heat database exists 
  mysql_db: name=heat state=present
  when: dbrole == 'master'
  
- name: Make sure heat user exists
  mysql_user: name=heat password={{ heat_database_password }} host="%" priv="heat.*:ALL" state=present
  when: dbrole == 'master'
  
- name: Install rabbitMQ
  apt: name=rabbitmq-server state=installed
  
- name: Make sure rabbitMQ is runing
  service: name=rabbitmq-server state=started enabled=yes
  
- name: Check if RabbitMQ is already clustered
  stat: path=/etc/rabbitmq/clustered
  register: rabbit_clustered
  
- include: rabbitmq_clustering.yaml
  when: rabbit_clustered.stat.exists != true
  
- name: Ensure openstack username and password exist or rabbitmq
  rabbitmq_user: user={{ rabbit_username }} password={{rabbit_password}} configure_priv=.* read_priv=.* write_priv=.* state=present

  
