---
- name: Get ubuntu keyring
  apt: name=ubuntu-cloud-keyring state=installed update_cache=yes
  
- name: Setup Heat repo
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/juno main' state=present
  
- name: Refresh dist
  apt: upgrade=dist update_cache=yes state=latest
  
- name: Install heat packages
  apt: name={{ item }} state=installed
  with_items:
   - heat-api
   - heat-api-cfn
   - heat-engine
   - python-heatclient
  notify: Restart server

- name: Waiting for server to come back
  local_action: wait_for port=22 host={{ inventory_hostname }}  delay=5
  sudo: false

- name: Copy heat configuration file
  template: src=heat.conf.j2 dest=/etc/heat/heat.conf
  notify: Restart heat services
  
- name: Create necessary heat databases
  command: sudo su -s /bin/sh -c "heat-manage db_sync" heat
  when: inventory_hostname  == heat_frontend1

  
# Install and configure keepalived
# then the only remainding point is to update the keystone catalog
