---
- name: Restart server
  command: shutdown -r now "Ansible triggered"
  async: 0
  poll: 0
  ignore_errors: true
  
- name: Restart heat services
  service: name={{ item }} state=restarted
  with_items:
    - heat-api
    - heat-engine

- name: Restart keepalived
  service: name=keepalived state=restarted
